# Generated by Django 2.2.19 on 2021-03-19 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference_reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceroom',
            name='projector',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.TextField(null=True)),
                ('conference_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference_reservation.ConferenceRoom')),
            ],
            options={
                'unique_together': {('date', 'conference_room')},
            },
        ),
    ]
